### PR TITLE
Show time out of sync error

### LINKED ISSUE #1065: Card can't be activated
**Describe the bug**
Some users report that they can not activate a card with the pdf. They receive the message: "Ihre Karte ist ungültig Sie wurde entweder widerrufen oder auf einem anderen Gerät aktiviert"

**To Reproduce**
Really difficult to reproduce because it seem to depend on the device or android version. We have to check if we get strange backend logs

**Expected behavior**
Card gets activated

Example card can be found in mattermost where the logs can be checked
https://chat.tuerantuer.org/digitalfabrik/pl/jkrgej4zot8zzru9uyggi5bbjc

### PR DESCRIPTION
**Pull request by michael-markl**
This should resolve #1065, #1056, #1049

When during self-verification, the time of the device is out of sync with the sever, the device would generate a wrong otp code and, thus, the server would respond that the card is not valid. The current app-store version (<= 3.1.3) of the app had the additional problem, that if the server responded once with "invalid", the app would not try to self-verify again the next time the app launches. This was already fixed by #1071 . This means, in the current dev-version (also before this PR), if you landed in this screen, resynced your local time, and restarted the app, the error would go away.

The solution I implemented here, is to simply analyze whether the time of the local device is out of sync at the time of self-verification. If so, we show a simple error like "Die Zeit deines Geräts scheint nicht zu stimmen. Synchronisiere deine Uhrzeit in den Geräte-Einstellungen."

### CODE REVIEW

File: frontend/lib/about/dev_settings_view.dart [hunk 1]
```diff
@@ -74,6 +77,10 @@ class DevSettingsView extends StatelessWidget {
             title: const Text('Set expired last card verification'),
             onTap: () => _setExpiredLastVerification(context),
           ),
+          ListTile(
+            title: const Text('Trigger self-verification'),
+            onTap: () => selfVerifyCard(userCodeModel, Configuration.of(context).projectId, client),
+          ),
```
Comment (sarahsporck) [inline frontend/lib/about/dev_settings_view.dart:83]: This was already implemented in the 'eine andere Karte verifizieren' screen. However, I also see no pain in having it in another place as well :)

**Review by sarahsporck — APPROVED** [review]
You genius :) works like charm! Very nice 👍🏼

File: frontend/lib/identification/verification_workflow/query_server_verification.dart [hunk 2]
```diff
@@ -3,19 +3,30 @@ import 'package:ehrenamtskarte/identification/util/card_info_utils.dart';
...
+  final timeBeforeRequest = DateTime.now();
+  final stopWatch = Stopwatch()..start();
+  final result = await _queryServerVerification(
     client,
     projectId,
     hash,
     verificationCode.otp,
     CodeType.kw$DYNAMIC,
   );
+  stopWatch.stop();
```
Comment (f1sh1918) [inline frontend/lib/identification/verification_workflow/query_server_verification.dart:22]: i think it would be nice to add a comment here

File: frontend/lib/about/dev_settings_view.dart (hunk 1 above)
Comment (michael-markl) [reply frontend/lib/about/dev_settings_view.dart:83]: I think in the "eine andere Karte verifizieren", it does not trigger the same process. Here, it triggers the self-verification process which also persists the card verification

**Comment by michael-markl** [comment]
> You genius :) works like charm! Very nice 👍🏼

Credit goes to @f1sh1918 for discovering that time-offset is the actual issue. :D Let's hope that this actually fixes all of the problems.

**Comment by f1sh1918** [comment]
> > You genius :) works like charm! Very nice 👍🏼
> 
> Credit goes to @f1sh1918 for discovering that time-offset is the actual issue. :D Let's hope that this actually fixes all of the problems.
> 

Hm not Sure if this also fixes the case when no activationTimestamp and totpSecret were written in the database but it's a super important fix :)

**Comment by michael-markl** [comment]
> Hm not Sure if this also fixes the case when no activationTimestamp and totpSecret were written in the database but it's a super important fix :)

True! I'm also not sure what happened there yet. That might actually be a different problem still :/
