### PR TITLE
1003: Datepicker shows wrong date

### LINKED ISSUE #1003: Datepicker shows wrong date
**Describe the bug**
In the card create form, the Datepicker shows a wrong date, when a date was typed in the input field

**To Reproduce**
1. Create cards
2. type in birthday
3. Check the Datepicker Date

**Expected behavior**
The date in the Datepicker reflects the typed date

**Screenshots**
image

### PR DESCRIPTION
**Pull request by f1sh1918**
- replace `DateInput` by MUI `TextField`

Testing:
Create cards for nbg and bavaria with new datepicker

resolves #1003

### CODE REVIEW

File: administration/src/cards/CardBlueprint.ts [hunk 1]
```diff
@@ -102,7 +102,9 @@ export class CardBlueprint implements JSONCardBlueprint {
     return new CardInfo({
       fullName: this.fullName,
       expirationDay:
-        expirationDate !== null && !this.hasInfiniteLifetime() ? dateToDaysSinceEpoch(expirationDate) : undefined,
+        expirationDate !== null && Date.parse(expirationDate.toISOString()) > 0 && !this.hasInfiniteLifetime()
```
Comment (sarahsporck) [inline administration/src/cards/CardBlueprint.ts:105]: why not 
```suggestion
        expirationDate !== null && expirationDate > 0 && !this.hasInfiniteLifetime()
```

**Review by sarahsporck — APPROVED** [review]
Tested in firefox

File: administration/src/cards/CardBlueprint.ts (hunk 1 above)
Comment (f1sh1918) [reply administration/src/cards/CardBlueprint.ts:105]: because i'm checking the milliseconds and not the date greater 0
