### PR TITLE
2983: Fix deeplinks

### LINKED ISSUE #2983: Creating multiple cards sets the same link for each QR code
### Describe the Bug

When I create multiple cards by entering the data in the admin UI, the activation QR code is the same for all cards.

### Steps to Reproduce

1. Go to '[Einzelne Karten erstellen](https://staging.bayern.ehrenamtskarte.app/cards/add)'
2. Add at least two cards.
3. Click on 'QR-Codes drucken'
4. Open the PDF and check the links for each QR code.
5. See error

### Expected Behavior

The data of the volunteer, the QR code and the activation deep-link should all belong together. No data 

### Additional Information

I created an example with current staging (although it's a production issue).

[berechtigungskarten.pdf](https://github.com/user-attachments/files/26888123/berechtigungskarten.pdf)

This also happens when importing cards as CSV.

### PR DESCRIPTION
**Pull request by f1sh1918**
### Short Description

This issue is a bit complicated and relies on what different types of page data there are in the pdf structure.
#### Content stream vs. Annotations
- Content stream: stores drawing commands (lines, rectangles, text). Each copied page gets its own fresh content stream. So drawRectangle (QR code) and drawText write into the page's own stream and stay isolated.    
--> not affected                                                                                              
Annots array: stores link annotations as entries in a shared PDFArray object referenced by a PDFRef. This is what addAnnot writes to. 
--> affected

### Proposed Changes

- enforce new cache by card to fix pdf annotations by calling `copyPage` per card

### Side Effects

- should be none

### Testing

1. Create multiple cards for bavaria (either over the form or bulk creation)
2. Open the pdf
3. Check that the deeplinks (hover on qr code) are different

### Resolved Issues

Fixes: #2983

### CODE REVIEW

**Comment by connium** [comment]
Maybe you want to add your findings in a code comment, so it doesn't get changed by accident in the future?

**Review by andrew8er — APPROVED** [review]

File: administration/src/cards/pdf/pdfFactory.ts [hunk 1]
```diff
@@ -131,12 +131,18 @@ export const generatePdf = async (
     targetDocument.setTitle(projectConfig.pdf.title)
     targetDocument.setAuthor(projectConfig.pdf.issuer)
 
-    const templatePages = await targetDocument.copyPages(
-      templateDocument,
-      Array.from({ length: codes.length }, () => 0),
-    )
+    /**
```
Comment (andrew8er) [inline administration/src/cards/pdf/pdfFactory.ts]: `/**` marks a documentation comment. I'd just use line comments (`//`) here.

**Review by steffenkleinle — APPROVED** [review]
LGTM, not tested

**Comment by f1sh1918** [comment]
did you test that pr @andrew8er 
One additional test would be good at least

File: administration/src/cards/pdf/pdfFactory.ts [hunk 2]
```diff
@@ -131,12 +131,16 @@ export const generatePdf = async (
...
+    // one call is expected to share object references (incl. Annots), causing all pages to end up
+    // with the same deep link annotation. Separate calls each create a fresh Copier that
+    // independently copies all referenced objects, giving every page its own Annots array.
+    const templatePages: PDFPage[] = []
     for (let i = 0; i < codes.length; i++) {
-      targetDocument.addPage(templatePages[i])
+      const [page] = await targetDocument.copyPages(templateDocument, [0])
+      targetDocument.addPage(page)
+      templatePages.push(page)
     }
```
Comment (andrew8er) [inline administration/src/cards/pdf/pdfFactory.ts:144]: I think, `map` could be used here:
```ts
const templatePages = codes.map(() => {
...
})
```

**Comment by andrew8er** [comment]
@f1sh1918 
Yes tested 👍

**Comment by Docmale** [comment]
Positive tested with multiple manual cards and CSV
